MD013:
  line_length: 300
  code_blocks: false
  tables: false
MD041: true
MD033: false  # Allow inline HTML
MD014: false  # Allow dollar signs in shell commands
MD025: false  # Allow multiple top-level headings
MD009: false  # Allow trailing spaces for line breaks
