name: Deploy MkDocs site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: |
          pip install --upgrade pip
          pip install uv

      - name: Install dependencies with uv
        run: |
          uv pip install --system mkdocs-material

      - name: Lint Markdown with markdownlint-cli2
        run: npx markdownlint-cli2 "**/*.md"

      - name: Check links with lychee-action
        uses: lycheeverse/lychee-action@v1.10.0
        with:
          args: --no-progress --exclude-mail --verbose './**/*.md'

      - name: Scan for secrets with gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --no-git --redact

      - name: Build and deploy
        run: |
          mkdocs gh-deploy --force 
